version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  influx:
    image: influxdb
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: sa
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: birb-inc
      DOCKER_INFLUXDB_INIT_BUCKET: bugged
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token-please-update
    volumes:
      - ./data/influx:/var/lib/influxdb2