version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  telegraf:
    image: telegraf
    ports:
      - '4317:4317'
      - '8094:8094'
    depends_on:
      - influxdb
    env_file:
      - influxv2.env
    volumes:
      - ./data/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
    env_file:
      - influxv2.env
    volumes:
      - ./data/influx:/var/lib/influxdb2
